-- Appends county/town text to address so derive_county()/derive_town() in
-- scripts/generate_landing_pages.py can place these rows on the right landing
-- pages. Source: Google Geocoding API formatted_address, already paid for and
-- cached in downloads/google_geocode_cache.json -- this migration costs nothing
-- extra. Review before running in the Supabase SQL editor.

-- County backfill (rows currently get NO county landing page at all)
update public.classes set address = 'Mount Merrion Community Centre, The Rise, Mount Merrion, Co. Dublin' where id = 13 and address = 'Mount Merrion Community Centre, The Rise, Mount Merrion';
update public.classes set address = 'Baldoyle Racecourse Community Centre, d13 x226, Co. Dublin' where id = 79 and address = 'Baldoyle Racecourse Community Centre, d13 x226';
update public.classes set address = 'Firhouse, Co. Dublin' where id = 81 and address = 'Firhouse';
update public.classes set address = 'Danville Business Park, Ring Rd, Co. Kilkenny' where id = 82 and address = 'Danville Business Park, Ring Rd';
update public.classes set address = 'Eastham Rd, Co. Meath' where id = 84 and address = 'Eastham Rd';
update public.classes set address = 'Clonard Community Centre, Clonard Rd, Co. Wexford' where id = 85 and address = 'Clonard Community Centre, Clonard Rd';
update public.classes set address = 'Camden Street Lower, Co. Dublin' where id = 86 and address = 'Camden Street Lower';
update public.classes set address = '6 Hynd''s Square, Co. Laois' where id = 88 and address = '6 Hynd''s Square';
update public.classes set address = 'Malahide Castle, Malahide Demesne, Co. Dublin' where id = 90 and address = 'Malahide Castle, Malahide Demesne';
update public.classes set address = 'Swords, Co. Dublin' where id = 91 and address = 'Swords';
update public.classes set address = 'Navan, Co. Meath' where id = 93 and address = 'Navan';
update public.classes set address = 'St. Peter''s GAA Dunboyne, Rooske Rd, Co. Meath' where id = 94 and address = 'St. Peter''s GAA Dunboyne, Rooske Rd';
update public.classes set address = 'Keadeen Hotel, Co. Kildare' where id = 95 and address = 'Keadeen Hotel';
update public.classes set address = 'Barleyhill, Co. Cork' where id = 96 and address = 'Barleyhill';
update public.classes set address = 'Pollamore Near, Co. Cavan' where id = 98 and address = 'Pollamore Near';
update public.classes set address = 'Julianstown Community Centre, Dimanistown West, Co. Meath' where id = 100 and address = 'Julianstown Community Centre, Dimanistown West';
update public.classes set address = 'Partas, Brookfield Enterprise Centre, Rossfield Ave, Co. Dublin' where id = 101 and address = 'Partas, Brookfield Enterprise Centre, Rossfield Ave';
update public.classes set address = 'Clontarf, Co. Dublin' where id = 102 and address = 'Clontarf';
update public.classes set address = 'Blue door, River Cottage, Wells lane, Gyles Quay, Ferrybank, Co. Louth' where id = 103 and address = 'Blue door, River Cottage, Wells lane, Gyles Quay, Ferrybank';
update public.classes set address = 'Glengoole, Co. Tipperary' where id = 107 and address = 'Glengoole';
update public.classes set address = 'Glengoole, Co. Tipperary' where id = 108 and address = 'Glengoole';
update public.classes set address = 'Roevehagh, Co. Galway' where id = 113 and address = 'Roevehagh';
update public.classes set address = 'Cúige Studios, 17-23 Dominick St, Co. Westmeath' where id = 114 and address = 'Cúige Studios, 17-23 Dominick St';
update public.classes set address = '30 Clanbrassil St, Co. Louth' where id = 115 and address = '30 Clanbrassil St';
update public.classes set address = 'Beach Court Kilcoole, Co. Wicklow' where id = 116 and address = 'Beach Court Kilcoole';
update public.classes set address = 'The Carraig Centre, Carraig Centre, Ballincollig, Co. Cork' where id = 117 and address = 'The Carraig Centre, Carraig Centre, Ballincollig';
update public.classes set address = '2 Monks Glade, Co. Wicklow' where id = 118 and address = '2 Monks Glade';
update public.classes set address = 'Lackenroe, Co. Cork' where id = 123 and address = 'Lackenroe';
update public.classes set address = 'Collis Sandes House, Killeen, Co. Kerry' where id = 124 and address = 'Collis Sandes House, Killeen';
update public.classes set address = 'Malahide, Co. Dublin' where id = 127 and address = 'Malahide';
update public.classes set address = '15West Street Drogheda, Co. Louth' where id = 132 and address = '15West Street Drogheda';
update public.classes set address = 'Malahide Community School, Broomfield, Co. Dublin' where id = 133 and address = 'Malahide Community School, Broomfield';
update public.classes set address = 'Highfield Rugby Club, Woodleigh Park, Co. Cork' where id = 135 and address = 'Highfield Rugby Club, Woodleigh Park';
update public.classes set address = 'Bounce Sports & Fitness Studio Tralee, Unit 3, Co. Kerry' where id = 136 and address = 'Bounce Sports & Fitness Studio Tralee, Unit 3';
update public.classes set address = 'IADT, Atrium Building, Dun Laoghaire Institute of Art Design and Technology, Kill Ave, Co. Dublin' where id = 137 and address = 'IADT, Atrium Building, Dun Laoghaire Institute of Art Design and Technology, Kill Ave';
update public.classes set address = 'Garryduff Sports Centre, Rochestown, Co. Cork' where id = 142 and address = 'Garryduff Sports Centre, Rochestown';
update public.classes set address = 'Ballinrea, Co. Cork' where id = 143 and address = 'Ballinrea';
update public.classes set address = 'Derrigra, Co. Cork' where id = 146 and address = 'Derrigra';
update public.classes set address = 'Harold''s Cross, Co. Dublin' where id = 147 and address = 'Harold''s Cross';
update public.classes set address = 'Lagavooren, Co. Louth' where id = 148 and address = 'Lagavooren';
update public.classes set address = 'Siamsa Tíre - Theatre & Arts Centre, Town Park, Co. Kerry' where id = 154 and address = 'Siamsa Tíre - Theatre & Arts Centre, Town Park';
update public.classes set address = 'Unit J3, Marina Commercial Park, Co. Cork' where id = 155 and address = 'Unit J3, Marina Commercial Park';
update public.classes set address = 'Blanchardstown, Co. Dublin' where id = 156 and address = 'Blanchardstown';
update public.classes set address = 'IADT Carriglea building, Kill Ave, Co. Dublin' where id = 158 and address = 'IADT Carriglea building, Kill Ave';
update public.classes set address = 'Barntick, Co. Clare' where id = 162 and address = 'Barntick';
update public.classes set address = 'St. Joseph''s Primary School, Marino Park Ave, Co. Dublin' where id = 163 and address = 'St. Joseph''s Primary School, Marino Park Ave';
update public.classes set address = 'St. Mary''s Youth and Community Centre, 2 Harbour St, Co. Offaly' where id = 164 and address = 'St. Mary''s Youth and Community Centre, 2 Harbour St';
update public.classes set address = '2nd Floor, FBD House, Mardyke St, Co. Westmeath' where id = 165 and address = '2nd Floor, FBD House, Mardyke St';
update public.classes set address = '10 Blackditch Rd, Co. Dublin' where id = 169 and address = '10 Blackditch Rd';
update public.classes set address = 'Taney Parish Centre., Co. Dublin' where id = 171 and address = 'Taney Parish Centre.';
update public.classes set address = 'Ballincollig, Co. Cork' where id = 173 and address = 'Ballincollig';
update public.classes set address = 'XVArena - XVAcademy Football Hub, Ballybane Industrial Estate, Unit 1 Ballybane Beg, Co. Galway' where id = 174 and address = 'XVArena - XVAcademy Football Hub, Ballybane Industrial Estate, Unit 1 Ballybane Beg';
update public.classes set address = 'Old Fort Rd, Co. Sligo' where id = 176 and address = 'Old Fort Rd';
update public.classes set address = 'k45 ve83, Co. Dublin' where id = 215 and address = 'k45 ve83';
update public.classes set address = 'Cross Guns Business Park Royal Canal Bank Phibsborough, Co. Dublin' where id = 447 and address = 'Cross Guns Business Park Royal Canal Bank Phibsborough';
update public.classes set address = 'Scoil Mhuire, 34 Griffith Avenue, Marino, Co. Dublin' where id = 453 and address = 'Scoil Mhuire, 34 Griffith Avenue, Marino';
update public.classes set address = 'St. Andrew’s Presbyterian, Church Hall, Mount Merrion Avenue, Blackrock, Co. Dublin' where id = 455 and address = 'St. Andrew’s Presbyterian, Church Hall, Mount Merrion Avenue, Blackrock';
update public.classes set address = 'Monkstown, Meadowbrook, Loughlinstown, Co. Dublin' where id = 478 and address = 'Monkstown, Meadowbrook, Loughlinstown';
update public.classes set address = 'Blackrock, Glenageary, Laughanstown, Co. Dublin' where id = 479 and address = 'Blackrock, Glenageary, Laughanstown';
update public.classes set address = 'Knocklyon, Dundrum, Sandyford, Rathfarnham, WestWood, Leopardstown, Co. Dublin' where id = 485 and address = 'Knocklyon, Dundrum, Sandyford, Rathfarnham, WestWood, Leopardstown';
update public.classes set address = 'Mountview Community Centre, Co. Dublin' where id = 488 and address = 'Mountview Community Centre';
update public.classes set address = 'Dundrum, Knocklyon, Rathfarnham, Co. Dublin' where id = 498 and address = 'Dundrum, Knocklyon, Rathfarnham';
update public.classes set address = 'Rosemont School Sandyford & Wesley College Sandyford, Co. Dublin' where id = 506 and address = 'Rosemont School Sandyford & Wesley College Sandyford';
update public.classes set address = 'Mounttown Community Facility in Dun Laoghaire, Co. Dublin' where id = 516 and address = 'Mounttown Community Facility in Dun Laoghaire';
update public.classes set address = 'Sandyford, Ballinteer, Monkstown, Co. Dublin' where id = 520 and address = 'Sandyford, Ballinteer, Monkstown';
update public.classes set address = '66D Heather Road, Sandyford, D18 W407, Co. Dublin' where id = 532 and address = '66D Heather Road, Sandyford, D18 W407';
update public.classes set address = 'Tallaght, Liffey Valley, Clontarf, Co. Dublin' where id = 564 and address = 'Tallaght, Liffey Valley, Clontarf';
update public.classes set address = '22A New Street, Killarney, Co. Kerry' where id = 565 and address = '22A New Street, Killarney';
update public.classes set address = 'Malahide Castle and Gardens, Malahide, Co. Dublin' where id = 1116 and address = 'Malahide Castle and Gardens, Malahide';
update public.classes set address = 'Holy Family Community Centre, Drogheda, Co. Louth' where id = 1385 and address = 'Holy Family Community Centre, Drogheda';
update public.classes set address = 'The Boyne Room, Millmount, Drogheda, Co. Louth' where id = 1386 and address = 'The Boyne Room, Millmount, Drogheda';
update public.classes set address = 'Old Abbey Dance Studios, Old Abbey Lane, Drogheda, Co. Louth' where id = 1388 and address = 'Old Abbey Dance Studios, Old Abbey Lane, Drogheda';
update public.classes set address = 'Holy Family Community Centre, Ballsgrove, Drogheda, Co. Louth' where id = 1389 and address = 'Holy Family Community Centre, Ballsgrove, Drogheda';
update public.classes set address = '1 Dunlin St, Aston Village, Drogheda, Co. Louth' where id = 1390 and address = '1 Dunlin St, Aston Village, Drogheda';
update public.classes set address = 'Unit 11 Blackthorn Business Park, Coe''s Road, Dundalk, Co. Louth' where id = 1391 and address = 'Unit 11 Blackthorn Business Park, Coe''s Road, Dundalk';
update public.classes set address = 'St Stephens School, Navan, Co. Meath' where id = 1395 and address = 'St Stephens School, Navan';
update public.classes set address = 'Unit 6 Beechmount, Homepark, Navan, Co. Meath' where id = 1396 and address = 'Unit 6 Beechmount, Homepark, Navan';
update public.classes set address = '84 Parnell Street, Ennis, Co. Clare' where id = 1406 and address = '84 Parnell Street, Ennis';
update public.classes set address = 'Collis Sandes House, Oakpark, Tralee, Co. Kerry' where id = 1421 and address = 'Collis Sandes House, Oakpark, Tralee';
update public.classes set address = 'Clahane, Ballyard, Tralee, Co. Kerry' where id = 1428 and address = 'Clahane, Ballyard, Tralee';
update public.classes set address = 'Flemington Community Centre, Hamlet Ln, Balbriggan, Co. Dublin' where id = 1431 and address = 'Flemington Community Centre, Hamlet Ln, Balbriggan';
update public.classes set address = '8 Hamptons Garden Avenue, Balbriggan, Co. Dublin' where id = 1433 and address = '8 Hamptons Garden Avenue, Balbriggan';
update public.classes set address = 'Castleland Community Centre, Balbriggan, Co. Dublin' where id = 1436 and address = 'Castleland Community Centre, Balbriggan';
update public.classes set address = 'Portlaoise Parish Centre, Stradbally Road, Portlaoise, Co. Laois' where id = 1445 and address = 'Portlaoise Parish Centre, Stradbally Road, Portlaoise';
update public.classes set address = 'Garden Vale, Athlone, Co. Westmeath' where id = 1448 and address = 'Garden Vale, Athlone';
update public.classes set address = 'Port Road, Letterkenny, Co. Donegal' where id = 1456 and address = 'Port Road, Letterkenny';
update public.classes set address = 'Cove Hill, Port Road, Letterkenny, Co. Donegal' where id = 1459 and address = 'Cove Hill, Port Road, Letterkenny';
update public.classes set address = 'Southern Cross Road, Bray, Co. Wicklow' where id = 1464 and address = 'Southern Cross Road, Bray';
update public.classes set address = 'St Patrick''s Church, Church Road, Greystones, Co. Wicklow' where id = 1469 and address = 'St Patrick''s Church, Church Road, Greystones';
update public.classes set address = 'Unit 6A, Ballyloughan Business Park, Arklow Rd, Gorey, Co. Wexford' where id = 1470 and address = 'Unit 6A, Ballyloughan Business Park, Arklow Rd, Gorey';
update public.classes set address = 'Unit E M4 Business Park, Celbridge, Co. Kildare' where id = 1489 and address = 'Unit E M4 Business Park, Celbridge';
update public.classes set address = 'Unit 15 The Avenue, St Wolstan''s Abbey, Celbridge, Co. Kildare' where id = 1490 and address = 'Unit 15 The Avenue, St Wolstan''s Abbey, Celbridge';
update public.classes set address = '38 Gladstone Street, Clonmel, Co. Tipperary' where id = 1499 and address = '38 Gladstone Street, Clonmel';
update public.classes set address = 'Cashel Road, Clonmel, Co. Tipperary' where id = 1500 and address = 'Cashel Road, Clonmel';
update public.classes set address = '1 Nelson Street, Clonmel, Co. Tipperary' where id = 1501 and address = '1 Nelson Street, Clonmel';
update public.classes set address = 'St. Mary''s Boys National School, Moyglare Road, Maynooth, Co. Kildare' where id = 1512 and address = 'St. Mary''s Boys National School, Moyglare Road, Maynooth';
update public.classes set address = 'Leixlip Parish Centre, Leixlip, Co. Kildare' where id = 1513 and address = 'Leixlip Parish Centre, Leixlip';
update public.classes set address = 'Leixlip and Youth Community Centre, Confey, Leixlip, Co. Kildare' where id = 1515 and address = 'Leixlip and Youth Community Centre, Confey, Leixlip';
update public.classes set address = 'Confey College, Leixlip, Co. Kildare' where id = 1516 and address = 'Confey College, Leixlip';
update public.classes set address = 'Tullamore Court Hotel, O''Moore St, Tullamore, Co. Offaly' where id = 1521 and address = 'Tullamore Court Hotel, O''Moore St, Tullamore';
update public.classes set address = 'Units 8 & 9, Ballinacurra Business Park, Midleton, Co. Cork' where id = 1531 and address = 'Units 8 & 9, Ballinacurra Business Park, Midleton';
update public.classes set address = 'Unit 1, Ballinacurra Business Park, Midleton, Co. Cork' where id = 1532 and address = 'Unit 1, Ballinacurra Business Park, Midleton';
update public.classes set address = 'Sandy Walk (MFRC), Broomfield Village, Midleton, Co. Cork' where id = 1533 and address = 'Sandy Walk (MFRC), Broomfield Village, Midleton';
update public.classes set address = 'Quarters Town Industrial Estate, Mallow, Co. Cork' where id = 1536 and address = 'Quarters Town Industrial Estate, Mallow';
update public.classes set address = 'Ballydahin, Quartertown, Mallow, Co. Cork' where id = 1539 and address = 'Ballydahin, Quartertown, Mallow';
update public.classes set address = 'Lough Lannagh, Castlebar, Co. Mayo' where id = 1546 and address = 'Lough Lannagh, Castlebar';
update public.classes set address = '15B, Breaffy Road Business Park, Castlebar, Co. Mayo' where id = 1548 and address = '15B, Breaffy Road Business Park, Castlebar';
update public.classes set address = 'Unit 1, Croghan Industrial Estate, Arklow, Co. Wicklow' where id = 1552 and address = 'Unit 1, Croghan Industrial Estate, Arklow';
update public.classes set address = 'St Aidan''s Hall, Irish Street, Enniscorthy, Co. Wexford' where id = 1554 and address = 'St Aidan''s Hall, Irish Street, Enniscorthy';
update public.classes set address = 'Convent Road, Enniscorthy, Co. Wexford' where id = 1557 and address = 'Convent Road, Enniscorthy';
update public.classes set address = 'Portmarnock Sports & Leisure Club, Blackwood Lane, Portmarnock, Co. Dublin' where id = 1581 and address = 'Portmarnock Sports & Leisure Club, Blackwood Lane, Portmarnock';
update public.classes set address = 'Portmarnock Sport and Leisure Club, Blackwood Lane, Portmarnock, Co. Dublin' where id = 1582 and address = 'Portmarnock Sport and Leisure Club, Blackwood Lane, Portmarnock';
update public.classes set address = 'Unit 4, The Stables Office Park, Portmarnock, Co. Dublin' where id = 1583 and address = 'Unit 4, The Stables Office Park, Portmarnock';
update public.classes set address = 'Monread Community Centre, Naas, Co. Kildare' where id = 1597 and address = 'Monread Community Centre, Naas';
update public.classes set address = 'W1K Ladytown Business Park, Toughers, Naas, Co. Kildare' where id = 1598 and address = 'W1K Ladytown Business Park, Toughers, Naas';
update public.classes set address = 'Unit 6, The Village Centre, Ratoath, Co. Meath' where id = 1609 and address = 'Unit 6, The Village Centre, Ratoath';
update public.classes set address = 'Ratoath Community Centre, Main St, Ratoath, Co. Meath' where id = 1611 and address = 'Ratoath Community Centre, Main St, Ratoath';
update public.classes set address = 'C.B.S Primary Nenagh, Co. Tipperary' where id = 1613 and address = 'C.B.S Primary Nenagh';
update public.classes set address = 'Unit 2 Church View, Summerhill, Nenagh, Co. Tipperary' where id = 1614 and address = 'Unit 2 Church View, Summerhill, Nenagh';
update public.classes set address = 'Scouts Den, Portrane Road, Donabate, Co. Dublin' where id = 1618 and address = 'Scouts Den, Portrane Road, Donabate';
update public.classes set address = 'Lambay House, Donabate, Co. Dublin' where id = 1619 and address = 'Lambay House, Donabate';
update public.classes set address = 'Donabate Portrane Educate Together National School, Co. Dublin' where id = 1620 and address = 'Donabate Portrane Educate Together National School';
update public.classes set address = 'St. Patrick''s Boys National School, Clane, Co. Kildare' where id = 1643 and address = 'St. Patrick''s Boys National School, Clane';
update public.classes set address = 'Scoil Phadraig, Clane, Co. Kildare' where id = 1644 and address = 'Scoil Phadraig, Clane';
update public.classes set address = 'Portmarnock Sports and Leisure Club, Blackwood Lane, Co. Dublin' where id = 1653 and address = 'Portmarnock Sports and Leisure Club, Blackwood Lane';
update public.classes set address = 'Kettle Memorial Park, Swords, Co. Dublin' where id = 1654 and address = 'Kettle Memorial Park, Swords';
update public.classes set address = 'Oak Centre, Castlefarm, Dunboyne, Co. Meath' where id = 1658 and address = 'Oak Centre, Castlefarm, Dunboyne';
update public.classes set address = 'Dunboyne Scout Den, Rooske Road, Dunboyne, Co. Meath' where id = 1659 and address = 'Dunboyne Scout Den, Rooske Road, Dunboyne';
update public.classes set address = 'The Exchange Inishowen, Buncrana, Co. Donegal' where id = 1661 and address = 'The Exchange Inishowen, Buncrana';
update public.classes set address = 'Eureka House, Kells, Co. Meath' where id = 1669 and address = 'Eureka House, Kells';
update public.classes set address = 'McNevin Ave, Ballinasloe, Co. Galway' where id = 1672 and address = 'McNevin Ave, Ballinasloe';
update public.classes set address = 'Town Hall Theatre, Ballinasloe, Co. Galway' where id = 1675 and address = 'Town Hall Theatre, Ballinasloe';
update public.classes set address = 'Moylough Community Resource Cultural and Heritage Centre, Ballinasloe, Co. Galway' where id = 1676 and address = 'Moylough Community Resource Cultural and Heritage Centre, Ballinasloe';
update public.classes set address = 'Crofty''s Yard, Main Street, Ballinasloe, Co. Galway' where id = 1677 and address = 'Crofty''s Yard, Main Street, Ballinasloe';
update public.classes set address = 'Star of the Sea School, Passage West, Co. Cork' where id = 1681 and address = 'Star of the Sea School, Passage West';
update public.classes set address = 'Garretstown Beach, near Kinsale, Co. Cork' where id = 1684 and address = 'Garretstown Beach, near Kinsale';
update public.classes set address = 'Saile Kinsale Sports and Community Centre, Kinsale, Co. Cork' where id = 1685 and address = 'Saile Kinsale Sports and Community Centre, Kinsale';
update public.classes set address = 'Calasanctius College, Castle Road, Oranmore, Co. Galway' where id = 1690 and address = 'Calasanctius College, Castle Road, Oranmore';
update public.classes set address = 'Comeragh College, Carrick-on-Suir, Co. Tipperary' where id = 1695 and address = 'Comeragh College, Carrick-on-Suir';
update public.classes set address = 'Comeragh College, Carrick On Suir, Co. Tipperary' where id = 1696 and address = 'Comeragh College, Carrick On Suir';
update public.classes set address = 'Carrick-On-Suir Library, Co. Tipperary' where id = 1697 and address = 'Carrick-On-Suir Library';
update public.classes set address = 'Oriel Rd, Drummond, Carrickmacross, Co. Monaghan' where id = 1699 and address = 'Oriel Rd, Drummond, Carrickmacross';
update public.classes set address = 'Civic Centre, Riverside Road, Carrickmacross, Co. Monaghan' where id = 1702 and address = 'Civic Centre, Riverside Road, Carrickmacross';
update public.classes set address = 'St Josephs Hall, Blessington Village, Co. Wicklow' where id = 1705 and address = 'St Josephs Hall, Blessington Village';
update public.classes set address = 'Main Street, Carrigtwohill, Co. Cork' where id = 1711 and address = 'Main Street, Carrigtwohill';
update public.classes set address = '14 Chestnut Crescent, Carrigtwohill, Co. Cork' where id = 1712 and address = '14 Chestnut Crescent, Carrigtwohill';
update public.classes set address = 'Streamstown, Roscrea, Co. Tipperary' where id = 1716 and address = 'Streamstown, Roscrea';
update public.classes set address = 'Ashe Rd, Nenagh North, Nenagh, Co. Tipperary' where id = 1727 and address = 'Ashe Rd, Nenagh North, Nenagh';
update public.classes set address = 'Clonakilty Sports Complex, Scartagh, Clonakilty, Co. Cork' where id = 1735 and address = 'Clonakilty Sports Complex, Scartagh, Clonakilty';
update public.classes set address = 'Carrigroe, Clonakilty, Co. Cork' where id = 1737 and address = 'Carrigroe, Clonakilty';
update public.classes set address = 'Flourish & Be, Main Street, Clonakilty, Co. Cork' where id = 1739 and address = 'Flourish & Be, Main Street, Clonakilty';
update public.classes set address = 'Mountmellick Library, O''Moore Street, Mountmellick, Co. Laois' where id = 1740 and address = 'Mountmellick Library, O''Moore Street, Mountmellick';
update public.classes set address = 'Scoil Mhuire Campus 1, Carrick-on-Shannon, Co. Leitrim' where id = 1746 and address = 'Scoil Mhuire Campus 1, Carrick-on-Shannon';

-- Town backfill (already have a county page, missing town-level page)
update public.classes set address = 'Ballycragh, Dublin, D24 YY0H, Ireland, Firhouse, Co. Dublin' where id = 256 and address = 'Ballycragh, Dublin, D24 YY0H, Ireland';
update public.classes set address = 'Howth Road, Dublin 5, Ireland, Clontarf, Co. Dublin' where id = 265 and address = 'Howth Road, Dublin 5, Ireland';
update public.classes set address = 'Temple Road, Dublin 6, Ireland, Rathmines, Co. Dublin' where id = 302 and address = 'Temple Road, Dublin 6, Ireland';
update public.classes set address = 'Aura De Paul Swimming Pool, St. Vincent''s Centre, Navan Road, Dublin 7, Castleknock, Co. Dublin' where id = 443 and address = 'Aura De Paul Swimming Pool, St. Vincent''s Centre, Navan Road, Dublin 7';
update public.classes set address = 'Main Street, Donnybrook, Dublin, D04 A0P1, Ireland, Rathfarnham, Co. Dublin' where id = 452 and address = 'Main Street, Donnybrook, Dublin, D04 A0P1, Ireland';
update public.classes set address = 'Pembroke Wanderers Hockey Club, Serpentine Ave., Dublin 4. D04 T329, Ballsbridge, Co. Dublin' where id = 531 and address = 'Pembroke Wanderers Hockey Club, Serpentine Ave., Dublin 4. D04 T329';
update public.classes set address = 'Danum, 6 Zion Rd, Rathgar, Dublin 6, D06 YR68, Ireland, Terenure, Co. Dublin' where id = 536 and address = 'Danum, 6 Zion Rd, Rathgar, Dublin 6, D06 YR68, Ireland';
update public.classes set address = 'West Cork Collective, Main St, Kinsale, Co. Cork' where id = 568 and address = 'West Cork Collective, Main St';
update public.classes set address = 'Leopardstown Tennis Club, Leopardstown, Dublin 18, Stillorgan, Co. Dublin' where id = 988 and address = 'Leopardstown Tennis Club, Leopardstown, Dublin 18';
update public.classes set address = 'Clonturk Community College, Whitehall, Dublin 9, Swords, Co. Dublin' where id = 995 and address = 'Clonturk Community College, Whitehall, Dublin 9';
update public.classes set address = 'Howth Road, Dublin 3, Ireland, Clontarf, Co. Dublin' where id = 1001 and address = 'Howth Road, Dublin 3, Ireland';
update public.classes set address = 'Mounttown, Dublin, Ireland, Monkstown, Co. Dublin' where id = 1086 and address = 'Mounttown, Dublin, Ireland';
update public.classes set address = 'Hillview Grove, Dublin, Ireland, Dundrum, Co. Dublin' where id = 1088 and address = 'Hillview Grove, Dublin, Ireland';
update public.classes set address = 'Churchtown School of Music, Dublin, Dundrum, Co. Dublin' where id = 1328 and address = 'Churchtown School of Music, Dublin';
