-- Adds star-rating support (1-5) for classes.
-- Run this once in the Supabase SQL editor (Project -> SQL Editor -> New query).
-- Nothing in this repo can create tables/policies via the REST API, so this has to be applied manually.

create table if not exists public.class_ratings (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  voter_id text not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (class_id, voter_id)
);

create index if not exists class_ratings_class_id_idx on public.class_ratings(class_id);

alter table public.class_ratings enable row level security;

create policy "Allow public read access" on public.class_ratings
  for select
  using (true);

-- No login system exists for parents, so "voter_id" is just a random ID the browser
-- generates and stores in localStorage -- it identifies a *browser*, not a real person.
-- These policies allow anyone to insert/update a rating row (needed for a no-login rating
-- widget to work at all), which means real abuse-resistance (one vote per actual person,
-- resistant to someone clearing localStorage or scripting requests) is NOT provided here.
-- This is a soft, friendly-nudge mechanism, not a security boundary. Tighten later if abuse
-- becomes a real problem (e.g. rate-limit by IP via an edge function, or require login).
create policy "Allow public insert (rate a class)" on public.class_ratings
  for insert
  with check (rating between 1 and 5);

create policy "Allow public update (change your own rating)" on public.class_ratings
  for update
  using (true)
  with check (rating between 1 and 5);
