-- Phase 1 admin upgrade: safer admin identity, soft-delete for businesses,
-- and an activity log for admin actions.
-- Run this once in the Supabase SQL editor.

-- ============================================================
-- 1. Admin identity and helper function
-- ============================================================
alter table public.admins
  add column if not exists user_id uuid;

create or replace function public.is_admin() returns boolean
language sql security definer set search_path = public as $$
  select exists (
    select 1
    from public.admins a
    where lower(a.email) = lower(auth.jwt() ->> 'email')
       or (a.user_id is not null and a.user_id = auth.uid())
  );
$$;
revoke execute on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- ============================================================
-- 2. Soft-delete support on classes
-- ============================================================
alter table public.classes
  add column if not exists is_deleted boolean not null default false,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

-- Hide deleted businesses from the public and from non-admins.
drop policy if exists "Allow public read access" on public.classes;
create policy "Allow public read access" on public.classes
  for select
  using (is_deleted = false or public.is_admin());

-- ============================================================
-- 3. Activity log table and RLS
-- ============================================================
create table if not exists public.admin_activity_log (
  id bigint generated by default as identity primary key,
  actor_email text not null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_activity_log enable row level security;

drop policy if exists "Admins can view activity log" on public.admin_activity_log;
create policy "Admins can view activity log" on public.admin_activity_log
  for select
  using (public.is_admin());

drop policy if exists "Admins can insert activity log" on public.admin_activity_log;
create policy "Admins can insert activity log" on public.admin_activity_log
  for insert
  with check (public.is_admin());

-- ============================================================
-- 4. Optional: keep admin rows visible and manageable
-- ============================================================
-- Existing admin-management policies continue to work. This just makes the
-- new `user_id` field available for future use without breaking current email-based access.
