// Map + age/price/free-only filters for category/county/combo landing pages
// (classes/*.html, generated by scripts/generate_landing_pages.py). One
// shared static file, same convention as styles.css/share.js -- the page's
// own result set is embedded as JSON (#landing-data) rather than fetched at
// runtime, since the page already knows it at generation time.
(function () {
    function escapeHtml(s) {
        return String(s || '').replace(/[&<>"']/g, function (c) {
            return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
        });
    }

    function readDataset() {
        var el = document.getElementById('landing-data');
        if (!el) return [];
        try {
            return JSON.parse(el.textContent) || [];
        } catch (e) {
            return [];
        }
    }

    // Two overlapping <input type=range> is the standard dependency-free way
    // to get a dual-handle slider: pointer-events is disabled on the input
    // itself (CSS) and re-enabled only on the ::-webkit-slider-thumb/
    // ::-moz-range-thumb, so each handle stays independently draggable
    // regardless of DOM order or z-index.
    function setupRangeSlider(container, onChange) {
        var minInput = container.querySelector('input:first-of-type');
        var maxInput = container.querySelector('input:last-of-type');
        var fill = container.querySelector('.range-track-fill');
        var rangeMin = parseFloat(minInput.min);
        var rangeMax = parseFloat(minInput.max);

        function paintFill(minVal, maxVal) {
            var pctMin = ((minVal - rangeMin) / (rangeMax - rangeMin)) * 100;
            var pctMax = ((maxVal - rangeMin) / (rangeMax - rangeMin)) * 100;
            fill.style.left = pctMin + '%';
            fill.style.right = (100 - pctMax) + '%';
        }

        function update() {
            var minVal = parseFloat(minInput.value);
            var maxVal = parseFloat(maxInput.value);
            if (minVal > maxVal) {
                if (document.activeElement === maxInput) {
                    minVal = maxVal;
                    minInput.value = String(minVal);
                } else {
                    maxVal = minVal;
                    maxInput.value = String(maxVal);
                }
            }
            paintFill(minVal, maxVal);
            onChange(minVal, maxVal, rangeMin, rangeMax);
        }

        minInput.addEventListener('input', update);
        maxInput.addEventListener('input', update);
        // Paint-only, deliberately not calling update()/onChange() here: at
        // construction time the caller's `var ageSlider = setupRangeSlider(...)`
        // assignment hasn't completed yet, so a callback that reads
        // ageSlider/priceSlider (both use this helper, and isDefaultState()
        // checks both) would blow up on the very first one. init() triggers
        // the real initial state explicitly once every slider exists instead.
        paintFill(rangeMin, rangeMax);

        return {
            bounds: { min: rangeMin, max: rangeMax },
            reset: function () {
                minInput.value = String(rangeMin);
                maxInput.value = String(rangeMax);
                paintFill(rangeMin, rangeMax);
            },
        };
    }

    function init() {
        var points = readDataset();
        if (!points.length) return;

        var filtersEl = document.getElementById('landing-filters');
        var cards = document.querySelectorAll('.landing-card[data-id]');
        var cardById = {};
        cards.forEach(function (card) {
            cardById[card.dataset.id] = card;
        });

        // ---- Map (optional -- only present when at least one row is geocoded) ----
        var map = null;
        var markerGroup = null;
        var mapEl = document.getElementById('landing-map');
        if (mapEl && typeof L !== 'undefined') {
            map = L.map('landing-map');
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; OpenStreetMap',
            }).addTo(map);
            renderMarkers(points);
        }

        function renderMarkers(visiblePoints) {
            if (!map) return;
            if (markerGroup) map.removeLayer(markerGroup);
            markerGroup = (typeof L.markerClusterGroup === 'function')
                ? L.markerClusterGroup({ maxClusterRadius: 50 })
                : L.layerGroup();
            var geoPoints = visiblePoints.filter(function (p) { return p.lat != null && p.lon != null; });
            geoPoints.forEach(function (p) {
                var marker = L.marker([p.lat, p.lon]);
                var popup = '<b>' + escapeHtml(p.name) + '</b>';
                if (p.category) popup += '<br>' + escapeHtml(p.category);
                popup += '<br><a href="' + p.url + '">View details &rarr;</a>';
                marker.bindPopup(popup);
                markerGroup.addLayer(marker);
            });
            map.addLayer(markerGroup);
            if (geoPoints.length === 1) {
                map.setView([geoPoints[0].lat, geoPoints[0].lon], 14);
            } else if (geoPoints.length > 1) {
                map.fitBounds(markerGroup.getBounds(), { padding: [30, 30] });
            }
        }

        if (!filtersEl) return; // Old cached page shell with no filter bar -- map-only is still fine.

        // ---- Filters ----
        var ageValueEl = document.getElementById('age-filter-value');
        var priceValueEl = document.getElementById('price-filter-value');
        var freeOnlyEl = document.getElementById('free-only');
        var resetBtn = document.getElementById('filters-reset');
        var noResultsReset = document.getElementById('no-results-reset');
        var noResultsMsg = document.getElementById('no-results-message');
        var countEl = document.getElementById('filters-count');

        var ageState = { min: 0, max: 18 };
        var priceState = { min: 0, max: 50 };

        var ageSlider = setupRangeSlider(document.querySelector('#landing-filters .filter-group:nth-child(1) .range-slider'), function (min, max, boundMin, boundMax) {
            ageState = { min: min, max: max };
            ageValueEl.textContent = (min === boundMin && max === boundMax)
                ? 'Any age' : (min + ' – ' + max + ' years');
            applyFilters();
        });
        var priceSlider = setupRangeSlider(document.querySelector('#landing-filters .filter-group:nth-child(2) .range-slider'), function (min, max, boundMin, boundMax) {
            priceState = { min: min, max: max };
            priceValueEl.textContent = (min === boundMin && max === boundMax)
                ? 'Any price' : ('€' + min + ' – €' + max + (max === boundMax ? '+' : ''));
            applyFilters();
        });

        function isDefaultState() {
            return ageState.min === ageSlider.bounds.min && ageState.max === ageSlider.bounds.max
                && priceState.min === priceSlider.bounds.min && priceState.max === priceSlider.bounds.max
                && !freeOnlyEl.checked;
        }

        function matches(p) {
            if (freeOnlyEl.checked && !p.free) return false;

            if (p.minAge != null || p.maxAge != null) {
                var rowMin = p.minAge != null ? p.minAge : 0;
                var rowMax = p.maxAge != null ? p.maxAge : 999;
                if (rowMax < ageState.min || rowMin > ageState.max) return false;
            }

            if (typeof p.price === 'number') {
                if (p.price < priceState.min || p.price > priceState.max) return false;
            } else if (p.free && priceState.min > 0) {
                return false;
            }

            return true;
        }

        function applyFilters() {
            var visiblePoints = [];
            var visibleCount = 0;
            points.forEach(function (p) {
                var ok = matches(p);
                var card = cardById[p.id];
                if (card) card.hidden = !ok;
                if (ok) {
                    visibleCount++;
                    visiblePoints.push(p);
                }
            });

            renderMarkers(visiblePoints);

            if (noResultsMsg) noResultsMsg.hidden = visibleCount !== 0;
            if (resetBtn) resetBtn.hidden = isDefaultState();
            if (countEl) {
                countEl.textContent = isDefaultState()
                    ? ''
                    : ('Showing ' + visibleCount + ' of ' + points.length + ' classes');
            }
        }

        function resetAll() {
            ageSlider.reset();
            priceSlider.reset();
            ageState = { min: ageSlider.bounds.min, max: ageSlider.bounds.max };
            priceState = { min: priceSlider.bounds.min, max: priceSlider.bounds.max };
            freeOnlyEl.checked = false;
            ageValueEl.textContent = 'Any age';
            priceValueEl.textContent = 'Any price';
            applyFilters();
        }

        freeOnlyEl.addEventListener('change', applyFilters);
        if (resetBtn) resetBtn.addEventListener('click', resetAll);
        if (noResultsReset) noResultsReset.addEventListener('click', resetAll);
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
