// Map + age/price/free-only filters for category/county/combo landing pages
// (classes/*.html, generated by scripts/generate_landing_pages.py). One
// shared static file, same convention as styles.css/share.js -- the page's
// own result set is embedded as JSON (#landing-data) rather than fetched at
// runtime, since the page already knows it at generation time.
(function () {
    function escapeHtml(s) {
        return String(s || '').replace(/[&<>"']/g, function (c) {
            return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
        });
    }

    function readDataset() {
        var el = document.getElementById('landing-data');
        if (!el) return [];
        try {
            return JSON.parse(el.textContent) || [];
        } catch (e) {
            return [];
        }
    }

    // setupRangeSlider() now lives in range-slider.js (shared with index.html's
    // main search page, which has the same Age/Price dual-slider filters) -- that
    // file is loaded before this one (see generate_landing_pages.py), so it's
    // already in scope here as a plain global function.

    function init() {
        var points = readDataset();
        if (!points.length) return;

        function track(eventName, params) {
            if (typeof window.trackEvent === 'function') window.trackEvent(eventName, params);
        }

        var filtersEl = document.getElementById('landing-filters');
        var cards = document.querySelectorAll('.landing-card[data-id]');
        var cardById = {};
        cards.forEach(function (card) {
            cardById[card.dataset.id] = card;
        });

        // ---- Map (optional -- only present when at least one row is geocoded) ----
        var map = null;
        var markerGroup = null;
        var mapEl = document.getElementById('landing-map');
        if (mapEl && typeof L !== 'undefined') {
            map = L.map('landing-map');
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; OpenStreetMap',
            }).addTo(map);
            renderMarkers(points);
        }

        function renderMarkers(visiblePoints) {
            if (!map) return;
            if (markerGroup) map.removeLayer(markerGroup);
            markerGroup = (typeof L.markerClusterGroup === 'function')
                ? L.markerClusterGroup({ maxClusterRadius: 50 })
                : L.layerGroup();
            var geoPoints = visiblePoints.filter(function (p) { return p.lat != null && p.lon != null; });
            geoPoints.forEach(function (p) {
                var marker = L.marker([p.lat, p.lon]);
                var popup = '<b>' + escapeHtml(p.name) + '</b>';
                if (p.category) popup += '<br>' + escapeHtml(p.category);
                popup += '<br><a href="' + p.url + '">View details &rarr;</a>';
                marker.bindPopup(popup);
                marker.on('click', function () { track('map_interaction', { action: 'marker_click', business_id: p.id }); });
                markerGroup.addLayer(marker);
            });
            map.addLayer(markerGroup);
            if (geoPoints.length === 1) {
                map.setView([geoPoints[0].lat, geoPoints[0].lon], 14);
            } else if (geoPoints.length > 1) {
                map.fitBounds(markerGroup.getBounds(), { padding: [30, 30] });
            }
        }

        if (!filtersEl) return; // Old cached page shell with no filter bar -- map-only is still fine.

        // ---- Filters ----
        var ageValueEl = document.getElementById('age-filter-value');
        var priceValueEl = document.getElementById('price-filter-value');
        var freeOnlyEl = document.getElementById('free-only');
        var resetBtn = document.getElementById('filters-reset');
        var noResultsReset = document.getElementById('no-results-reset');
        var noResultsMsg = document.getElementById('no-results-message');
        var countEl = document.getElementById('filters-count');

        var ageState = { min: 0, max: 18 };
        var priceState = { min: 0, max: 50 };

        var ageSlider = setupRangeSlider(document.querySelector('#landing-filters .filter-group:nth-child(1) .range-slider'), function (min, max, boundMin, boundMax) {
            ageState = { min: min, max: max };
            ageValueEl.textContent = (min === boundMin && max === boundMax)
                ? 'Any age' : (min + ' – ' + max + ' years');
            applyFilters();
        }, function () {
            track('filter_used', { filter_type: 'age', min: ageState.min, max: ageState.max });
        });
        var priceSlider = setupRangeSlider(document.querySelector('#landing-filters .filter-group:nth-child(2) .range-slider'), function (min, max, boundMin, boundMax) {
            priceState = { min: min, max: max };
            priceValueEl.textContent = (min === boundMin && max === boundMax)
                ? 'Any price' : ('€' + min + ' – €' + max + (max === boundMax ? '+' : ''));
            applyFilters();
        }, function () {
            track('filter_used', { filter_type: 'price', min: priceState.min, max: priceState.max });
        });

        function isDefaultState() {
            return ageState.min === ageSlider.bounds.min && ageState.max === ageSlider.bounds.max
                && priceState.min === priceSlider.bounds.min && priceState.max === priceSlider.bounds.max
                && !freeOnlyEl.checked;
        }

        function matches(p) {
            if (freeOnlyEl.checked && !p.free) return false;

            if (p.minAge != null || p.maxAge != null) {
                var rowMin = p.minAge != null ? p.minAge : 0;
                var rowMax = p.maxAge != null ? p.maxAge : 999;
                if (rowMax < ageState.min || rowMin > ageState.max) return false;
            }

            if (typeof p.price === 'number') {
                if (p.price < priceState.min || p.price > priceState.max) return false;
            } else if (p.free && priceState.min > 0) {
                return false;
            }

            return true;
        }

        // Rebuilding the marker cluster group + map.fitBounds() is expensive enough
        // that running it synchronously on every single 'input' tick while dragging a
        // range slider makes the browser fall behind on pointer events -- visible as
        // the slider handle itself jumping/stuttering rather than tracking the cursor
        // smoothly. Debounced so it settles shortly after dragging pauses instead of
        // running on every pixel of drag.
        var renderMarkersTimer = null;
        function scheduleRenderMarkers(visiblePoints) {
            clearTimeout(renderMarkersTimer);
            renderMarkersTimer = setTimeout(function () {
                renderMarkers(visiblePoints);
            }, 150);
        }

        function applyFilters() {
            var visiblePoints = [];
            var visibleCount = 0;
            points.forEach(function (p) {
                var ok = matches(p);
                var card = cardById[p.id];
                if (card) card.hidden = !ok;
                if (ok) {
                    visibleCount++;
                    visiblePoints.push(p);
                }
            });

            scheduleRenderMarkers(visiblePoints);

            if (noResultsMsg) noResultsMsg.hidden = visibleCount !== 0;
            if (resetBtn) resetBtn.hidden = isDefaultState();
            if (countEl) {
                countEl.textContent = isDefaultState()
                    ? ''
                    : ('Showing ' + visibleCount + ' of ' + points.length + ' classes');
            }
        }

        function resetAll() {
            ageSlider.reset();
            priceSlider.reset();
            ageState = { min: ageSlider.bounds.min, max: ageSlider.bounds.max };
            priceState = { min: priceSlider.bounds.min, max: priceSlider.bounds.max };
            freeOnlyEl.checked = false;
            ageValueEl.textContent = 'Any age';
            priceValueEl.textContent = 'Any price';
            applyFilters();
        }

        freeOnlyEl.addEventListener('change', function () {
            track('filter_used', { filter_type: 'free', value: freeOnlyEl.checked });
            applyFilters();
        });
        if (resetBtn) resetBtn.addEventListener('click', resetAll);
        if (noResultsReset) noResultsReset.addEventListener('click', resetAll);
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
