-- Adds an `individual_classes` table so an owner can list the specific classes/
-- sessions they run (as opposed to the single summary row per business in
-- `classes`), plus RLS scoping all writes to the approved owner of that
-- business -- mirrors the pattern already used for the `classes` UPDATE policy
-- in portal_security_and_storage.sql.
--
-- Run this once in the Supabase SQL editor.

create table if not exists public.individual_classes (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.classes(id) on delete cascade,
  name text,
  start_date date,
  duration_weeks integer,
  day text,
  time text,
  min_age numeric,
  max_age numeric,
  num_classes integer,
  price_per_class numeric,
  price_per_term numeric,
  created_at timestamptz not null default now()
);

create index if not exists individual_classes_business_id_idx on public.individual_classes(business_id);

alter table public.individual_classes enable row level security;

drop policy if exists "Allow public read access" on public.individual_classes;
create policy "Allow public read access" on public.individual_classes
  for select
  using (true);

drop policy if exists "Approved owners can insert their business's classes" on public.individual_classes;
create policy "Approved owners can insert their business's classes" on public.individual_classes
  for insert
  with check (
    exists (
      select 1 from public.claim_requests cr
      where cr.business_id::text = individual_classes.business_id::text
        and cr.status = 'approved'
        and lower(cr.requester_email) = lower(auth.jwt() ->> 'email')
    )
  );

drop policy if exists "Approved owners can update their business's classes" on public.individual_classes;
create policy "Approved owners can update their business's classes" on public.individual_classes
  for update
  using (
    exists (
      select 1 from public.claim_requests cr
      where cr.business_id::text = individual_classes.business_id::text
        and cr.status = 'approved'
        and lower(cr.requester_email) = lower(auth.jwt() ->> 'email')
    )
  )
  with check (
    exists (
      select 1 from public.claim_requests cr
      where cr.business_id::text = individual_classes.business_id::text
        and cr.status = 'approved'
        and lower(cr.requester_email) = lower(auth.jwt() ->> 'email')
    )
  );

drop policy if exists "Approved owners can delete their business's classes" on public.individual_classes;
create policy "Approved owners can delete their business's classes" on public.individual_classes
  for delete
  using (
    exists (
      select 1 from public.claim_requests cr
      where cr.business_id::text = individual_classes.business_id::text
        and cr.status = 'approved'
        and lower(cr.requester_email) = lower(auth.jwt() ->> 'email')
    )
  );
