// Shared "Share" icon row for business detail pages (business/*.html,
// generated by scripts/generate_business_pages.py). One static file
// referenced by every generated page rather than inlined per page -- same
// convention as styles.css.
(function () {
    function fallbackCopy(text) {
        var ta = document.createElement('textarea');
        ta.value = text;
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.focus();
        ta.select();
        try { document.execCommand('copy'); } catch (e) { /* ignore */ }
        document.body.removeChild(ta);
    }

    function initShareRow(row) {
        var title = row.dataset.title || document.title;
        var url = row.dataset.url || window.location.href;
        var businessId = row.dataset.businessId;

        function track(platform) {
            if (typeof window.trackEvent === 'function') {
                window.trackEvent('share_click', { platform: platform, business_id: businessId });
            }
        }

        var links = {
            whatsapp: 'https://wa.me/?text=' + encodeURIComponent(title + ' — ' + url),
            facebook: 'https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(url),
            x: 'https://twitter.com/intent/tweet?text=' + encodeURIComponent(title) + '&url=' + encodeURIComponent(url),
            email: 'mailto:?subject=' + encodeURIComponent(title) + '&body=' + encodeURIComponent(url),
        };
        Object.keys(links).forEach(function (key) {
            var el = row.querySelector('[data-share="' + key + '"]');
            if (el) {
                el.href = links[key];
                el.addEventListener('click', function () { track(key); });
            }
        });

        var copyBtn = row.querySelector('[data-share="copy"]');
        if (copyBtn) {
            copyBtn.addEventListener('click', function () {
                track('copy');
                var showCopied = function () {
                    copyBtn.classList.add('copied');
                    setTimeout(function () { copyBtn.classList.remove('copied'); }, 1600);
                };
                if (navigator.clipboard && navigator.clipboard.writeText) {
                    navigator.clipboard.writeText(url).then(showCopied).catch(function () {
                        fallbackCopy(url);
                        showCopied();
                    });
                } else {
                    fallbackCopy(url);
                    showCopied();
                }
            });
        }
    }

    function init() {
        document.querySelectorAll('.share-row').forEach(initShareRow);
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
