-- Backfill real coordinates for existing rows in public.classes.
-- Generated by geocoding each unique address via OpenStreetMap Nominatim (2026-07-30).
-- Matches on company_name + address since classes has no natural key shared with the JSON export.
-- Run this in the Supabase SQL editor.

update public.classes set latitude = 53.2880835, longitude = -6.3731227 where company_name = 'Doodlebox' and address = 'Rua Red South Dublin Arts Centre, Blessington Road, Tallaght, Dublin 24';
update public.classes set latitude = 53.2612843, longitude = -6.1505691 where company_name = 'Wild by Nature Forest School' and address = 'Cabinteely Park (Bray Road entrance), Cabinteely, Dublin 18';
update public.classes set latitude = 53.3115981, longitude = -6.282925 where company_name = 'Dublin School of Music' and address = 'Eaton House, 86-88 Terenure Road North, Terenure, Dublin 6W';
update public.classes set latitude = 53.2882188, longitude = -6.18887 where company_name = 'Dublin School of Music' and address = '20 Kilmacud Road Lower, Stillorgan, Dublin 18';
update public.classes set latitude = 53.2878082, longitude = -6.362355 where company_name = 'Dublin School of Music' and address = 'Units 15/16 Old Bawn Shopping Centre, Tallaght, Dublin 24';
update public.classes set latitude = 53.3579826, longitude = -6.4323748 where company_name = 'Lucan School of Music' and address = 'Colaiste Phadraig CBS, Roselawn, Lucan, Co. Dublin';
update public.classes set latitude = 53.2914036, longitude = -6.2341717 where company_name = 'Baby Sensory South Dublin' and address = 'Taney Parish Centre, Taney Road, Dundrum, Dublin 14';
update public.classes set latitude = 53.261135, longitude = -6.1500827 where company_name = 'Baby Sensory South Dublin' and address = 'St Brigid''s, Cabinteely, Co. Dublin';
update public.classes set latitude = 53.2973285, longitude = -6.2807096 where company_name = 'Baby Sensory Dublin Southwest' and address = 'The Ruah Centre, Rathfarnham, Dublin';
update public.classes set latitude = 53.2880835, longitude = -6.3731227 where company_name = 'Baby Sensory Dublin Southwest' and address = 'Rua Red South Dublin Arts Centre, Blessington Road, Tallaght, Dublin 24';
update public.classes set latitude = 53.2740278, longitude = -6.3434547 where company_name = 'Baby Sensory Dublin Southwest' and address = 'The Park Community Centre, Firhouse, Dublin 24';
update public.classes set latitude = 53.2959279, longitude = -6.2093475 where company_name = 'Dimples Baby Massage' and address = 'Mount Merrion Community Centre, The Rise, Mount Merrion';
update public.classes set latitude = 53.2990832, longitude = -6.173857 where company_name = 'Bloom Baby Classes (Dublin South)' and address = 'Little Roo, 6 Temple Road, Blackrock, Co. Dublin';
update public.classes set latitude = 53.2355191, longitude = -6.1933991 where company_name = 'Play Cafe / Bumps and Babes' and address = 'Kilternan, Dublin 18';
update public.classes set latitude = 53.3010201, longitude = -6.1761325 where company_name = 'Talls and Smalls' and address = 'Urban Junction, Main Street, Blackrock, Co. Dublin';
update public.classes set latitude = 53.2698337, longitude = -6.2245713 where company_name = 'Baby Talk' and address = 'Sandyford, Dublin 18';
update public.classes set latitude = 53.2888378, longitude = -6.198343 where company_name = 'Honey Bee Hive' and address = 'Stillorgan, Co. Dublin';
update public.classes set latitude = 53.2753673, longitude = -6.2367372 where company_name = 'Wobblers and Toddlers' and address = 'Balally Family Resource Centre, Sandyford, Dublin 16';
update public.classes set latitude = 53.3007756, longitude = -6.1754274 where company_name = 'Blackrock Library Parent and Toddler Group' and address = 'Blackrock Library, Blackrock, Co. Dublin';
update public.classes set latitude = 53.2335312, longitude = -6.127023 where company_name = 'Shankill Library Parent and Toddler Group' and address = 'Shankill Library, Library Road, Shankill, Co. Dublin';
update public.classes set latitude = 53.277345, longitude = -6.1045475 where company_name = 'Dalkey Library Parent and Toddler Group' and address = 'Dalkey Library, Dalkey, Co. Dublin';
update public.classes set latitude = 53.2926299, longitude = -6.2468491 where company_name = 'Dundrum Library Parent and Toddler Group' and address = 'Dundrum Library, Dundrum, Dublin 14';
update public.classes set latitude = 53.2775617, longitude = -6.1646684 where company_name = 'Deansgrange Library Parent and Toddler Group' and address = 'Deansgrange Library, Deansgrange, Co. Dublin';
update public.classes set latitude = 53.2582951, longitude = -6.1971705 where company_name = 'Ballyogan Community Development Group Parent and Toddler Group' and address = 'Ballyogan, Dublin 18';
update public.classes set latitude = 53.2914036, longitude = -6.2341717 where company_name = 'Artzone' and address = 'Taney Parish Centre, Taney Road, Dundrum, Dublin 14';
update public.classes set latitude = 53.2981262, longitude = -6.2857372 where company_name = 'Kidspace Rathfarnham' and address = 'Kidspace PlayCentre, 20 Main Street, Rathfarnham, Dublin';
update public.classes set latitude = 53.2875214, longitude = -6.3278175 where company_name = 'Ballyboden St Endas GAA, Camogie & Ladies Football Club' and address = 'Ballyboden St Endas GAA, Firhouse Road, Dublin 16';
update public.classes set latitude = 53.2973285, longitude = -6.2807096 where company_name = 'Leinster Rugby (Bank of Ireland Leinster Rugby Summer Camps)' and address = 'Stillorgan-Rathfarnham RFC, Heavey Technology Park, Tibradden Road, Rathfarnham, Dublin 16';
update public.classes set latitude = 53.2866424, longitude = -6.1995825 where company_name = 'Kilmacud Crokes GAA Club' and address = 'Glenalbyn House, Glenalbyn Road, Stillorgan, Co. Dublin';
update public.classes set latitude = 53.2763447, longitude = -6.3409028 where company_name = 'Little Kickers Dublin & Meath' and address = 'Firhouse Community Centre, Ballycullen Drive, Firhouse, Dublin 24';
update public.classes set latitude = 53.2869192, longitude = -6.1631364 where company_name = 'Little Kickers Dublin & Meath' and address = 'Rockford Manor Secondary School, Stradbrook Road, Blackrock, Co. Dublin';
update public.classes set latitude = 53.3222703, longitude = -6.2800697 where company_name = 'Little Kickers Dublin & Meath' and address = 'The Spawell Complex, Templeogue, Dublin';
update public.classes set latitude = 53.2782328, longitude = -6.215602 where company_name = 'First Swim' and address = '10 The Plaza, Beacon South Quarter, Sandyford Business Park, Dublin 18';
update public.classes set latitude = 53.2832142, longitude = -6.3919939 where company_name = 'SCD Leisure Tallaght (Tallaght Leisure Centre)' and address = 'Fortunestown Way, Tallaght, Dublin 24';
update public.classes set latitude = 53.2877775, longitude = -6.3517811 where company_name = 'South Dublin Dance Academy' and address = 'Tallaght Enterprise Centre, Main Road, Tallaght, Dublin 24';
update public.classes set latitude = 53.2917252, longitude = -6.2748554 where company_name = 'Kate Buckley School of Dance' and address = 'Rathfarnham Educate Together National School, Loreto Avenue, Rathfarnham, Dublin 14';
update public.classes set latitude = 53.2786477, longitude = -6.1749969 where company_name = 'Junior Einsteins Science Club (South Dublin)' and address = 'Lycee Francais International Samuel Beckett, Foxrock Avenue, Newpark, Foxrock, Co. Dublin';
update public.classes set latitude = 53.3018639, longitude = -6.1788342 where company_name = 'Trojan Gymnastic Club' and address = '7/8 Holly Avenue, Stillorgan Business Park, Blackrock, Co. Dublin';
update public.classes set latitude = 53.2678414, longitude = -6.2627252 where company_name = 'Dundrum South Dublin Athletic Club (DSD)' and address = 'Tibradden Road, Taylorsgrange, Dublin 16';
update public.classes set latitude = 53.2797317, longitude = -6.1086608 where company_name = 'Cuala GAA Club' and address = 'Hyde Park, Hyde Road, Dalkey, Co. Dublin';
update public.classes set latitude = 53.2467012, longitude = -6.1975246 where company_name = 'De La Salle Palmerston FC (DLSP)' and address = 'Kirwan Park, Kilternan, Dublin 18';
